"""Create the PostgreSQL ledger tables.

Revision ID: 0002_ledger_tables
Revises: 0001_storage_meta
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002_ledger_tables"
down_revision = "0001_storage_meta"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "runs",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("deployment_id", sa.Text()),
        sa.Column("workflow_id", sa.Text(), nullable=False),
        sa.Column("package_digest", sa.Text(), nullable=False),
        sa.Column("binding_digest", sa.Text()),
        sa.Column("plan_json", sa.Text(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("control_mode", sa.Text(), nullable=False),
        sa.Column("deadline_at", sa.Text(), nullable=False),
        sa.Column("next_attempt_at", sa.Text()),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("current_node_id", sa.Text()),
        sa.Column("current_scope_id", sa.Text()),
        sa.Column("current_invocation_id", sa.Text()),
        sa.Column("rerun_of", sa.Text(), sa.ForeignKey("runs.id")),
        sa.Column("rerun_reason", sa.Text()),
        sa.Column("output_json", sa.Text()),
        sa.Column("error_json", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False, server_default="local-user"),
        sa.Column("resource_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("resource_version", sa.Integer()),
        sa.Column("before_version", sa.Integer()),
        sa.Column("after_version", sa.Integer()),
        sa.Column("transition", sa.Text()),
        sa.Column("error_json", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
    )
    op.create_index(
        "uq_commands_scope_key",
        "commands",
        ["namespace", "subject", "operation", "idempotency_key"],
        unique=True,
    )
    op.create_table(
        "scopes",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("parent_scope_id", sa.Text(), sa.ForeignKey("scopes.id")),
        sa.Column("parent_invocation_id", sa.Text()),
        sa.Column("workflow_id", sa.Text(), nullable=False),
        sa.Column("path_json", sa.Text(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text()),
        sa.Column("error_json", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
    )
    op.create_table(
        "invocations",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text()),
        sa.Column("error_json", sa.Text()),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("scope_id", "node_id", name="uq_invocations_scope_node"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id"), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("dispatch_key", sa.Text(), nullable=False),
        sa.Column("effect_key", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text()),
        sa.Column("error_json", sa.Text()),
        sa.Column("external_ref", sa.Text()),
        sa.Column("observation_revision", sa.Integer()),
        sa.Column("observation_json", sa.Text()),
        sa.Column("next_attempt_at", sa.Text()),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("reconciliation_json", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("dispatch_key", name="uq_attempts_dispatch_key"),
        sa.UniqueConstraint("invocation_id", "attempt_no", name="uq_attempts_invocation_no"),
    )
    op.create_table(
        "human_requests",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id"), nullable=False),
        sa.Column("request_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.Text(), nullable=False),
        sa.Column("subject_digest", sa.Text(), nullable=False),
        sa.Column("choices_json", sa.Text(), nullable=False),
        sa.Column("decision_schema_json", sa.Text(), nullable=False),
        sa.Column("authorized_subjects_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("decision_id", sa.Text()),
        sa.Column("updated_at", sa.Text()),
    )
    op.create_table(
        "codex_interactions",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id"), nullable=False),
        sa.Column("attempt_id", sa.Text(), sa.ForeignKey("attempts.id"), nullable=False),
        sa.Column("native_request_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("turn_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("authorized_subjects_json", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text()),
        sa.Column("response_digest", sa.Text()),
        sa.Column("invalid_reason", sa.Text()),
        sa.Column("actor", sa.Text()),
        sa.Column("idempotency_key", sa.Text(), unique=True),
        sa.Column("delivery_status", sa.Text(), nullable=False, server_default="not_sent"),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("attempt_id", "native_request_id", name="uq_codex_attempt_request"),
    )
    op.create_table(
        "human_decisions",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("request_id", sa.Text(), sa.ForeignKey("human_requests.id"), nullable=False),
        sa.Column("request_version", sa.Integer(), nullable=False),
        sa.Column("choice", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("decision_json", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("subject_digest", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("request_id", name="uq_human_decisions_request"),
    )
    op.create_table(
        "human_progress_intents",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("request_id", sa.Text(), sa.ForeignKey("human_requests.id"), nullable=False),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id"), nullable=False),
        sa.Column("decision_id", sa.Text(), sa.ForeignKey("human_decisions.id"), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("request_id", name="uq_human_progress_request"),
        sa.UniqueConstraint("decision_id", name="uq_human_progress_decision"),
    )
    op.create_table(
        "waits",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("wait_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id")),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id")),
        sa.Column("not_before", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("worker_id", sa.Text()),
        sa.Column("claimed_at", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("namespace", "wait_key", name="uq_waits_namespace_key"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("action_key", sa.Text(), nullable=False, unique=True),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id"), nullable=False),
        sa.Column(
            "attempt_id",
            sa.Text(),
            sa.ForeignKey("attempts.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("payload_digest", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("external_ref", sa.Text()),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_attempt_at", sa.Text()),
        sa.Column("last_error_json", sa.Text()),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("scope_id", sa.Text(), sa.ForeignKey("scopes.id")),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id")),
        sa.Column("attempt_id", sa.Text(), sa.ForeignKey("attempts.id")),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.Text(), nullable=False),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_seq"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("namespace", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), sa.ForeignKey("runs.id"), nullable=False),
        sa.Column("invocation_id", sa.Text(), sa.ForeignKey("invocations.id")),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("digest", sa.Text(), nullable=False),
        sa.Column("storage_ref", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
    )
    op.create_table(
        "external_artifact_sources",
        sa.Column("attempt_id", sa.Text(), sa.ForeignKey("attempts.id"), nullable=False),
        sa.Column("execution_ref", sa.Text(), nullable=False),
        sa.Column("source_artifact_id", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column(
            "artifact_id",
            sa.Text(),
            sa.ForeignKey("artifacts.id"),
            nullable=False,
            unique=True,
        ),
        sa.PrimaryKeyConstraint(
            "attempt_id", "execution_ref", "source_artifact_id", "version"
        ),
    )


def downgrade() -> None:
    for table in (
        "external_artifact_sources",
        "artifacts",
        "run_events",
        "outbox",
        "waits",
        "human_progress_intents",
        "human_decisions",
        "codex_interactions",
        "human_requests",
        "attempts",
        "invocations",
        "scopes",
        "commands",
        "runs",
    ):
        op.drop_table(table)
